name: Clone and Build External Repository

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: 克隆外部仓库
      - name: Clone external repository
        run: |
          git clone https://github.com/PCL-Community/PCL2-CE external-repo
          cd external-repo
          dir

      # Step 2: 设置 MSBuild 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # Step 3: 恢复 NuGet 包
      - name: Restore NuGet packages
        run: |
          cd external-repo
          nuget restore "Plain Craft Launcher 2.sln"

      # Step 4: 编译解决方案
      - name: Build Solution
        run: |
          cd external-repo
          msbuild "Plain Craft Launcher 2.sln" /p:Configuration=Release

      # Step 5: 列出编译后的文件
      - name: List compiled files
        run: |
          cd external-repo/Plain Craft Launcher 2/bin

      # Step 6: 上传编译结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: external-repo/Plain Craft Launcher 2/bin # 指定正确的输出文件夹
