name: Clone, Build and Upload Artifacts

on:
  push:
    branches:
      - main  # 或者你的目标分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: 克隆当前仓库
      - name: Checkout current repository
        uses: actions/checkout@v3

      # Step 2: 克隆外部仓库
      - name: Clone external repository
        run: |
          git clone https://github.com/PCL-Community/PCL2-CE external-repo
          cd external-repo
          dir  # 列出文件，确认 .sln 文件存在

      # Step 3: 设置 MSBuild 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # Step 4: 恢复 NuGet 包
      - name: Restore NuGet packages
        run: |
          cd external-repo
          nuget restore "Plain Craft Launcher 2.sln"

      # Step 5: 编译解决方案
      - name: Build Solution
        run: |
          cd external-repo
          msbuild "Plain Craft Launcher 2.sln" /p:Configuration=Release
          dir /s

      # Step 6: 上传构建结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: external-repo/bin/Release  # 这里路径根据你的实际输出文件路径来修改
