name: Build and Package PCL2.Nova.App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone PCL2.Nova.App repository
      run: git clone https://github.com/PCL-Community/PCL2.Nova.App.git

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: cargo
        override: true

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install dependencies
      run: |
        cd PCL2.Nova.App
        pnpm install

    - name: Build the Windows version
      run: |
        cd PCL2.Nova.App
        pnpm tauri build --target windows

    - name: Archive the build
      uses: actions/upload-artifact@latest
      with:
        name: PCL2-Nova-App-Windows-Build
        path: PCL2.Nova.App/target/tauri/windows/*
