name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装系统依赖 (Linux 需要额外步骤)
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev patchelf

      # 安装 Node.js 和 pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm@8

      # 安装 Rust (Tauri 依赖)
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      # 缓存优化
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: |
            node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install

      # 构建项目
      - name: Build with Tauri
        run: pnpm tauri build

      # 上传构建产物
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ runner.os }}
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.app.tar.gz
            src-tauri/target/release/*.msi
          if-no-files-found: error