name: Build and Upload PCL2 Nova App

on:
  workflow_dispatch:
    inputs:
      build_platform:
        description: 'Build target platform'
        default: 'windows'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: PCL-Community/PCL2.Nova.App
        path: PCL2.Nova.App

    # Step 2: Setup Node.js and pnpm
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    # Step 3: Install Rust nightly and ensure correct version
    - name: Install Rust nightly
      run: |
        rustup install nightly
        rustup default nightly

    - name: Ensure Rust version
      run: rustc --version
      shell: pwsh

    # Step 4: Install dependencies
    - name: Install dependencies
      run: pnpm install
      working-directory: ./PCL2.Nova.App

    # Step 5: Build the application (Windows only)
    - name: Build for Windows
      run: pnpm tauri build
      working-directory: ./PCL2.Nova.App

    # Step 6: Archive the built repository
    - name: Archive repository
      run: |
        Compress-Archive -Path ./PCL2.Nova.App/* -DestinationPath ./PCL2_Nova_App_Build.zip
      shell: pwsh

    # Step 7: Upload artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: PCL2_Nova_App_Build
        path: ./PCL2_Nova_App_Build.zip
