name: PCL2.Neo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: 克隆外部仓库
      - name: Clone external repository
        run: |
          git clone https://github.com/PCL-Community/PCL2.Neo external-repo
          cd external-repo
          dir

      # Step 2: 替换字体文件
      - name: Replace Font.ttf
        run: |
          echo ${GITHUB_WORKSPACE}
          ls ${GITHUB_WORKSPACE}/neo
          mkdir -Force "external-repo/Resources"
          Copy-Item -Path "${GITHUB_WORKSPACE}/neo/MiSans-Normal.ttf" -Destination "external-repo/Resources/Font.ttf" -Force
          dir "external-repo/Resources"

      # Step 3: 设置 MSBuild 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # Step 4: 恢复 NuGet 包
      - name: Restore NuGet packages
        run: |
          nuget restore "external-repo/PCL2.Neo.sln"

      # Step 5: 编译解决方案
      - name: Build Solution
        run: |
          msbuild "external-repo/PCL2.Neo.sln" /p:Configuration=Release

      # Step 6: 压缩整个项目文件夹
      - name: Archive project folder
        run: |
          Compress-Archive -Path "external-repo/*" -DestinationPath "external-repo.zip"

      # Step 7: 上传压缩文件
      - name: Upload archived project
        uses: actions/upload-artifact@v3
        with:
          name: project-archive
          path: external-repo.zip
